FROM node:22-alpine3.21 AS build

WORKDIR /app

COPY server/package*.json ./

RUN npm ci

COPY server/ ./

RUN npm run build

FROM node:22-alpine3.21

WORKDIR /app

COPY server/package*.json ./

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

EXPOSE 5000

CMD ["node", "dist/main"]
