FROM node:22-alpine3.21 AS build

WORKDIR /app

COPY client/package*.json ./

RUN npm ci

COPY client/ ./

RUN npm run build

FROM node:22-alpine3.21

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist /app

EXPOSE 3000

CMD ["serve", "-s", ".", "-l", "3000"]
