version: '3.8'

services:
  client:
    image: node:22-alpine3.21
    working_dir: /app
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    command: sh -c "npm install && npm run dev -- --host --open"
    networks:
      - app-network

  server:
    image: node:22-alpine3.21
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/github_crm
      - JWT_SECRET=dev_jwt_secret_key_here
      - NODE_ENV=development
    command: sh -c "if [ -f package.json ]; then npm install && npm run start:dev; else echo 'No package.json found. Make sure server directory contains a valid NestJS project'; fi"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  client_node_modules:
